trigger:
- none  # Trigger is defined in schedule, no auto trigger on push.

schedules:
- cron: "0 0 * * *"  # This triggers every day at midnight (adjust the cron expression as needed).
  displayName: "Daily Trigger"
  branches:
    include:
      - main

variables:
  uniqueTimestamp: "$(Build.BuildId)"  # Using Build.BuildId as unique identifier
  jtlFileName: "result-$(Build.BuildId).jtl"  # JTL file name using BuildId
  reportFolderName: "jmeter-report-$(Build.BuildId)"  # Unique report folder name using BuildId

stages:
  - stage: Prepare
    jobs:
      - job: PrepareEnvironment
        pool:
          vmImage: 'windows-latest'  # Change to Windows VM
        steps:
          - script: |
              echo Installing JMeter...
              curl -L https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.zip -o jmeter.zip
              powershell -Command "Expand-Archive -Path jmeter.zip -DestinationPath ."
              set JMETER_HOME=%cd%\apache-jmeter-5.6.3
              echo "##vso[task.setvariable variable=JMETER_HOME]%JMETER_HOME%"
            displayName: 'Install JMeter 5.6.3'

  - stage: CheckoutCode
    jobs:
      - job: CheckoutGitHub
        pool:
          vmImage: 'windows-latest'  # Change to Windows VM
        steps:
          - checkout: self  # Checkout code from repository
          - script: |
              git clone https://github.com/RohitReghunath/AzureDevOps_Demo.git
              cd AzureDevOps_Demo
            displayName: 'Clone GitHub Repository and Checkout Test Scripts'

  - stage: RunJMeterTest
    jobs:
      - job: RunTest
        pool:
          vmImage: 'windows-latest'  # Change to Windows VM
        steps:
          - checkout: self
          - script: |
              echo Running JMeter test...
              "%JMETER_HOME%\bin\jmeter.bat" -n -t "%cd%\AzureDevOps_Demo\Jpetstore_Demo.jmx" -l "%cd%\$(Build.ArtifactStagingDirectory)\$(jtlFileName)"
            displayName: 'Run JMeter Performance Test'

  - stage: GenerateReport
    jobs:
      - job: GenerateHTMLReport
        pool:
          vmImage: 'windows-latest'  # Change to Windows VM
        steps:
          - script: |
              echo Generating JMeter report...
              "%JMETER_HOME%\bin\jmeter.bat" -g "%cd%\$(Build.ArtifactStagingDirectory)\$(jtlFileName)" -o "%cd%\$(Build.ArtifactStagingDirectory)\$(reportFolderName)"
            displayName: 'Generate JMeter HTML Report'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\$(reportFolderName)'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)\$(reportFolderName).zip'
            displayName: 'Compress and Archive JMeter Report'

  - stage: Cleanup
    jobs:
      - job: CleanupEnvironment
        pool:
          vmImage: 'windows-latest'  # Change to Windows VM
        steps:
          - script: |
              # Clean up temporary files
              rmdir /s /q apache-jmeter-5.6.3
              del "$(Build.ArtifactStagingDirectory)\$(jtlFileName)"
            displayName: 'Cleanup Temporary Files'