pool:
  vmImage: 'windows-latest'

variables:
  JMETER_VERSION: '5.6.3'
  JMETER_HOME: '$(Build.SourcesDirectory)\apache-jmeter-$(JMETER_VERSION)'
  TEST_SCRIPT: 'Jpetstore_Demo.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'jmeter-report'

stages:
- stage: InstallJMeter
  displayName: 'Install JMeter'
  jobs:
    - job: InstallJMeter
      steps:
        - script: |
            echo Installing JMeter on Windows...
            cd "$(Build.SourcesDirectory)"
            curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$(JMETER_VERSION).zip -o jmeter.zip
            tar -xf jmeter.zip
            dir
          displayName: 'Download & Extract JMeter'

- stage: RunJMeterTest
  displayName: 'Run JMeter Test'
  dependsOn: InstallJMeter
  jobs:
    - job: RunTest
      steps:
        - script: |
            echo Running JMeter Test on Windows...
            cd "$(Build.SourcesDirectory)"
            call "$(JMETER_HOME)\bin\jmeter.bat" -n -t "$(Build.SourcesDirectory)\$(TEST_SCRIPT)" -l "$(Build.SourcesDirectory)\$(RESULTS_FILE)" -e -o "$(Build.SourcesDirectory)\$(REPORT_DIR)"
          displayName: 'Run JMeter Test'

- stage: PublishResults
  displayName: 'Publish Results'
  dependsOn: RunJMeterTest
  jobs:
    - job: PublishResults
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\$(REPORT_DIR)'
            ArtifactName: 'JMeterResults'
            publishLocation: 'Container'
