trigger:
  branches:
    include:
      - main  # This will trigger the pipeline on commits to the main branch

pool:
  vmImage: 'windows-latest'  # Using a Microsoft-hosted Windows agent

variables:
  JMETER_HOME: 'C:\\apache-jmeter-5.6.3\\bin'  # Correct path for Windows-based agent
  TEST_SCRIPT: 'Jpetstore_Demo.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'jmeter-report'

stages:
- stage: RunJMeterTest
  displayName: 'Run JMeter Test'
  jobs:
    - job: RunTest
      steps:
        - script: |
            echo "Running JMeter Test on Windows..."
            "%JMETER_HOME%\\jmeter.bat" -n -t $(TEST_SCRIPT) -l $(RESULTS_FILE) -e -o $(REPORT_DIR)
          displayName: 'Run JMeter Test'

- stage: PublishResults
  displayName: 'Publish Results'
  jobs:
    - job: PublishResults
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/$(REPORT_DIR)'
            ArtifactName: 'JMeterResults'
            publishLocation: 'Container'
