pool:
  vmImage: 'windows-latest'

variables:
  JMETER_HOME: '$(Build.SourcesDirectory)\apache-jmeter-5.6.3'
  TEST_SCRIPT: 'Jpetstore_Demo.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'jmeter-report'

stages:
- stage: InstallJMeter
  displayName: 'Install JMeter'
  jobs:
    - job: InstallJMeter
      steps:
        - script: |
            echo Installing JMeter on Windows...
            curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip -o jmeter.zip
            tar -xf jmeter.zip
          displayName: 'Download & Extract JMeter'

- stage: RunJMeterTest
  displayName: 'Run JMeter Test'
  jobs:
    - job: RunTest
      steps:
        - script: |
            echo Running JMeter Test on Windows...
            call "$(JMETER_HOME)\bin\jmeter.bat" -n -t $(TEST_SCRIPT) -l $(RESULTS_FILE) -e -o $(REPORT_DIR)
          displayName: 'Run JMeter Test'

- stage: PublishResults
  displayName: 'Publish Results'
  jobs:
    - job: PublishResults
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\$(REPORT_DIR)'
            ArtifactName: 'JMeterResults'
            publishLocation: 'Container'
