trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to main branch

pool:
  vmImage: 'windows-latest'  # Use Windows agent

variables:
  JMETER_HOME: 'C:\apache-jmeter-5.6.3\bin'
  TEST_SCRIPT: 'Jpetstore_Demo.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'jmeter-report'

stages:
- stage: InstallJMeter
  displayName: 'Install JMeter'
  jobs:
    - job: InstallJMeter
      steps:
        - powershell: |
            Write-Host "Installing JMeter..."
            Invoke-WebRequest -Uri https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip -OutFile apache-jmeter.zip
            Expand-Archive -Path apache-jmeter.zip -DestinationPath C:\
          displayName: 'Install JMeter'

- stage: RunJMeterTest
  displayName: 'Run JMeter Test'
  jobs:
    - job: RunTest
      steps:
        - script: |
            echo Running JMeter Test on Windows...
            call "$(JMETER_HOME)\jmeter.bat" -n -t $(TEST_SCRIPT) -l $(RESULTS_FILE) -e -o $(REPORT_DIR)
          displayName: 'Run JMeter Test'

- stage: PublishResults
  displayName: 'Publish Results'
  jobs:
    - job: PublishResults
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\$(REPORT_DIR)'
            ArtifactName: 'JMeterResults'
            publishLocation: 'Container'
