trigger:
  branches:
    include:
      - main  # This will trigger the pipeline on commits to the main branch

pool:
  vmImage: 'windows-latest'  # Using a Microsoft-hosted Windows agent

variables:
  JMETER_HOME: 'C:\\apache-jmeter-5.6.3\\bin'  # Correct path for Windows agents
  TEST_SCRIPT: 'Jpetstore_Demo.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'jmeter-report'

stages:
- stage: InstallJMeter
  displayName: 'Install JMeter'
  jobs:
    - job: InstallJMeter
      steps:
        - powershell: |
            echo "Installing JMeter..."
            $url = "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip"
            $output = "apache-jmeter-5.6.3.zip"
            Invoke-WebRequest -Uri $url -OutFile $output
            Expand-Archive -Path $output -DestinationPath 'C:\'
            # Check if JMeter exists after extraction
            if (Test-Path "C:\apache-jmeter-5.6.3\bin\jmeter.bat") {
              Write-Host "JMeter successfully installed!"
            } else {
              Write-Host "JMeter installation failed!"
            }
          displayName: 'Install JMeter'

- stage: RunJMeterTest
  displayName: 'Run JMeter Test'
  jobs:
    - job: RunTest
      steps:
        - script: |
            echo "Running JMeter Test on Windows..."
            if (Test-Path "%JMETER_HOME%\\jmeter.bat") {
              "%JMETER_HOME%\\jmeter.bat" -n -t $(TEST_SCRIPT) -l $(RESULTS_FILE) -e -o $(REPORT_DIR)
            } else {
              echo "JMeter not found at %JMETER_HOME%"
              exit 1
            }
          displayName: 'Run JMeter Test'

- stage: PublishResults
  displayName: 'Publish Results'
  jobs:
    - job: PublishResults
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/$(REPORT_DIR)'
            ArtifactName: 'JMeterResults'
            publishLocation: 'Container'
