trigger:
  branches:
    include:
      - main  # Runs pipeline on commits to main

pool:
  name: Default  # Use the self-hosted agent pool

variables:
  JMETER_VERSION: '5.6.3'
  JMETER_HOME: 'C:\\apache-jmeter-$(JMETER_VERSION)'  # Set local JMeter path
  TEST_SCRIPT: 'PetStore.jmx'
  RESULTS_FILE: 'results.jtl'
  REPORT_DIR: 'html-report'

steps:
  # Show Pipeline.Workspace Path
  - task: PowerShell@2
    displayName: 'Show Pipeline.Workspace Path'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Pipeline.Workspace: $(Pipeline.Workspace)"
        Write-Host "Build.SourcesDirectory: $(Build.SourcesDirectory)"

  # Skip download step as JMeter is already locally available
  - task: PowerShell@2
    displayName: 'Set JMETER_HOME'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Setting JMETER_HOME to: $(JMETER_HOME)"
        
  # Run JMeter Test Plan
  - task: PowerShell@2
    displayName: 'Run JMeter Test Plan'
    inputs:
      targetType: 'inline'
      script: |
        $env:JMETER_HOME = "$(JMETER_HOME)"
        Write-Host "JMETER_HOME is set to: $env:JMETER_HOME"
        cd "$env:JMETER_HOME\\bin"
        .\jmeter.bat -n -t "$(Build.SourcesDirectory)\\$(TEST_SCRIPT)" -l "$(Build.SourcesDirectory)\\$(RESULTS_FILE)" -e -o "$(Build.SourcesDirectory)\\$(REPORT_DIR)"

  # Publish JMeter Results
  - task: PublishBuildArtifacts@1
    displayName: 'Publish JMeter Results'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\\$(REPORT_DIR)'
      ArtifactName: 'JMeterReport'
      publishLocation: 'Container'
